language: node_js
sudo: required
node_js:
  - lts/*
branch: master
cache:
  directories:
    - node_modules
before_install:
 - chmod +x deploy.sh
install:
    - npm install vitepress
script:
  - ./deploy.sh